/* =====================================
   QUESTIONS DATA - QUIZ RAMADHAN
   ===================================== */

const questions = [
  /* ================= TK ================= */
  {
    level: "TK",
    q: "Puasa dilakukan pada bulan apa?",
    options: ["Ramadhan", "Syawal", "Rajab", "Safar"],
    correct: 0,
  },
  {
    level: "TK",
    q: "Saat puasa kita tidak boleh makan sampai ...",
    options: ["Siang", "Maghrib", "Subuh", "Dzuhur"],
    correct: 1,
  },
  {
    level: "TK",
    q: "Puasa dimulai saat adzan ...",
    options: ["Maghrib", "Isya", "Subuh", "Ashar"],
    correct: 2,
  },
  {
    level: "TK",
    q: "Makan sebelum puasa disebut ...",
    options: ["Berbuka", "Sahur", "Sarapan", "Makan siang"],
    correct: 1,
  },
  {
    level: "TK",
    q: "Makan saat maghrib disebut ...",
    options: ["Berbuka", "Sahur", "Tidur", "Snack"],
    correct: 0,
  },
  {
    level: "TK",
    q: "Sholat malam di bulan Ramadhan disebut ...",
    options: ["Jumat", "Tahajud", "Dhuha", "Tarawih"],
    correct: 3,
  },
  {
    level: "TK",
    q: "Orang yang puasa mendapat ...",
    options: ["Mainan", "Pahala", "Uang", "Hadiah"],
    correct: 1,
  },
  {
    level: "TK",
    q: "Saat puasa kita harus berkata ...",
    options: ["Baik", "Marah", "Berteriak", "Kasar"],
    correct: 0,
  },
  {
    level: "TK",
    q: "Jika lupa makan saat puasa maka puasanya ...",
    options: ["Batal", "Tetap Sah", "Dimarahi", "Harus ulang"],
    correct: 1,
  },
  {
    level: "TK",
    q: "Bulan Ramadhan adalah bulan yang ...",
    options: ["Gelap", "Biasa", "Sedih", "Istiwewa"],
    correct: 3,
  },
  {
    level: "TK",
    q: "Puasa mengajarkan kita untuk ...",
    options: ["Sabar", "Marah", "Bertengkar", "Nakal"],
    correct: 0,
  },
  {
    level: "TK",
    q: "Kita berbuka saat adzan ...",
    options: ["Subuh", "Maghrib", "Dzuhur", "Ashar"],
    correct: 1,
  },
  {
    level: "TK",
    q: "Al-Qur'an diturunkan pada bulan ...",
    options: ["Muharram", "Rajab", "Ramadhan", "Safar"],
    correct: 2,
  },
  {
    level: "TK",
    q: "Saat puasa kita tidak boleh ...",
    options: ["Minum", "Belajar", "Sholat", "Mengaji"],
    correct: 0,
  },
  {
    level: "TK",
    q: "Anak yang belajar puasa disebut ...",
    options: ["Hebat", "Malas", "Nakalan", "Sedih"],
    correct: 0,
  },

  /* ================= SD1 ================= */
  {
    level: "SD1",
    q: "Puasa Ramadhan adalah rukun Islam yang ke ...",
    options: ["Dua", "Tiga", "Empat", "Lima"],
    correct: 2,
  },
  {
    level: "SD1",
    q: "Puasa dilakukan dari terbit fajar sampai ...",
    options: ["Dzuhur", "Ashar", "Maghrib", "Isya"],
    correct: 2,
  },
  {
    level: "SD1",
    q: "Niat puasa dilakukan pada waktu ...",
    options: ["Pagi hari", "Siang hari", "Malam hari", "Sore hari"],
    correct: 2,
  },
  {
    level: "SD1",
    q: "Makan sebelum imsak disebut ...",
    options: ["Berbuka", "Jajan", "Sarapan", "Sahur"],
    correct: 3,
  },
  {
    level: "SD1",
    q: "Jika sengaja makan saat puasa maka puasanya ...",
    options: ["Sah", "Batal", "Baik saja", "Tidak apa-apa"],
    correct: 1,
  },
  {
    level: "SD1",
    q: "Orang yang sedang sakit boleh tidak berpuasa dan harus ...",
    options: [
      "Diam saja",
      "Mengganti di hari lain",
      "Tidak usah puasa lagi",
      "Bayar uang",
    ],
    correct: 1,
  },
  {
    level: "SD1",
    q: "Sholat sunnah di bulan Ramadhan disebut ...",
    options: ["Dhuha", "Tarawih", "Tahajud", "Witir saja"],
    correct: 1,
  },
  {
    level: "SD1",
    q: "Berbuka puasa sebaiknya diawali dengan ...",
    options: ["Permen", "Nasi", "Kurma", "Mie"],
    correct: 2,
  },
  {
    level: "SD1",
    q: "Puasa melatih kita untuk bersikap ...",
    options: ["Marah", "Sabar", "Bertengkar", "Malas"],
    correct: 1,
  },
  {
    level: "SD1",
    q: "Bulan Ramadhan disebut juga bulan ...",
    options: ["Biasa", "Hujan", "Penuh berkah", "Liburan"],
    correct: 2,
  },
  {
    level: "SD1",
    q: "Membaca Al-Qur'an di bulan Ramadhan mendapat pahala yang ...",
    options: ["Sedikit", "Biasa", "Kurang", "Banyak"],
    correct: 3,
  },
  {
    level: "SD1",
    q: "Orang yang lupa makan saat puasa maka puasanya ...",
    options: ["Batal", "Tetap sah", "Harus ulang", "Dimarahi"],
    correct: 1,
  },
  {
    level: "SD1",
    q: "Saat puasa kita tidak boleh berkata ...",
    options: ["Baik", "Jujur", "Kasar", "Sopan"],
    correct: 2,
  },
  {
    level: "SD1",
    q: "Zakat fitrah dibayarkan pada bulan ...",
    options: ["Ramadhan", "Muharram", "Safar", "Rajab"],
    correct: 0,
  },
  {
    level: "SD1",
    q: "Puasa membuat kita merasakan ...",
    options: ["Kekenyangan", "Kesombongan", "Lapar dan haus", "Kemalasan"],
    correct: 2,
  },
  /* ================= SD2 ================= */
  {
    level: "SD2",
    q: "Puasa Ramadhan hukumnya ...",
    options: ["Sunnah", "Wajib", "Makruh", "Mubah"],
    correct: 1,
  },
  {
    level: "SD2",
    q: "Puasa termasuk rukun Islam yang ke ...",
    options: ["Dua", "Tiga", "Empat", "Lima"],
    correct: 2,
  },
  {
    level: "SD2",
    q: "Orang yang wajib puasa adalah yang sudah ...",
    options: ["Baligh", "Tidur", "Sakit", "Bepergian"],
    correct: 0,
  },
  {
    level: "SD2",
    q: "Menahan diri dari makan dan minum disebut ...",
    options: ["Sholat", "Puasa", "Zakat", "Sedekah"],
    correct: 1,
  },
  {
    level: "SD2",
    q: "Puasa dimulai sejak terbit ...",
    options: ["Matahari", "Fajar", "Bulan", "Bintang"],
    correct: 1,
  },
  {
    level: "SD2",
    q: "Puasa berakhir saat matahari ...",
    options: ["Terbit", "Tinggi", "Tenggelam", "Bersinar"],
    correct: 2,
  },
  {
    level: "SD2",
    q: "Orang yang sedang safar boleh ...",
    options: [
      "Tidak puasa dan mengganti",
      "Tidak puasa selamanya",
      "Tetap makan saja",
      "Tidak sholat",
    ],
    correct: 0,
  },
  {
    level: "SD2",
    q: "Menyegerakan berbuka adalah ...",
    options: ["Makruh", "Haram", "Wajib", "Sunnah"],
    correct: 3,
  },
  {
    level: "SD2",
    q: "Makan dan minum dengan sengaja saat puasa menyebabkan ...",
    options: ["Pahala bertambah", "Puasa batal", "Tidak apa-apa", "Puasa sah"],
    correct: 1,
  },
  {
    level: "SD2",
    q: "Bulan Ramadhan disebut bulan ...",
    options: ["Ilmu", "Perjuangan", "Penuh ampunan", "Liburan"],
    correct: 2,
  },
  {
    level: "SD2",
    q: "Ibadah membaca Al-Qur'an di Ramadhan disebut ...",
    options: ["Tilawah", "Zakat", "Haji", "Sedekah"],
    correct: 0,
  },
  {
    level: "SD2",
    q: "Sholat witir biasanya dilakukan setelah ...",
    options: ["Subuh", "Tarawih", "Dzuhur", "Ashar"],
    correct: 1,
  },
  {
    level: "SD2",
    q: "Orang yang tidak berpuasa karena sakit wajib ...",
    options: [
      "Membayar fidyah saja",
      "Diam saja",
      "Mengganti puasa",
      "Tidak usah apa-apa",
    ],
    correct: 2,
  },
  {
    level: "SD2",
    q: "Puasa melatih kita untuk ...",
    options: ["Sabar dan jujur", "Marah", "Malas", "Bertengkar"],
    correct: 0,
  },
  {
    level: "SD2",
    q: "Zakat fitrah dibayarkan sebelum sholat ...",
    options: ["Jumat", "Tarawih", "Subuh", "Idul Fitri"],
    correct: 3,
  },

  /* ================= SD3 ================= */
  {
    level: "SD3",
    q: "Niat puasa Ramadhan dilakukan pada waktu ...",
    options: ["Siang hari", "Malam hari", "Sore hari", "Dzuhur"],
    correct: 1,
  },
  {
    level: "SD3",
    q: "Syarat wajib puasa salah satunya adalah ...",
    options: ["Islam", "Kaya", "Tinggi", "Pintar"],
    correct: 0,
  },
  {
    level: "SD3",
    q: "Syarat sah puasa salah satunya adalah ...",
    options: ["Baligh", "Berakal", "Kaya", "Islam"],
    correct: 3,
  },
  {
    level: "SD3",
    q: "Hal yang membatalkan puasa adalah ...",
    options: ["Tidur", "Makan sengaja", "Belajar", "Sholat"],
    correct: 1,
  },
  {
    level: "SD3",
    q: "Jika muntah dengan sengaja maka puasa ...",
    options: ["Sah", "Batal", "Makruh", "Sunnah"],
    correct: 1,
  },
  {
    level: "SD3",
    q: "Lailatul Qadar terjadi pada bulan ...",
    options: ["Muharram", "Rajab", "Ramadhan", "Safar"],
    correct: 2,
  },
  {
    level: "SD3",
    q: "Puasa Ramadhan diwajibkan pada tahun ke ... hijriyah",
    options: ["1", "2", "3", "4"],
    correct: 1,
  },
  {
    level: "SD3",
    q: "Orang tua renta boleh tidak puasa dan membayar ...",
    options: ["Zakat", "Fidyah", "Haji", "Sedekah"],
    correct: 1,
  },
  {
    level: "SD3",
    q: "Puasa sunnah Senin Kamis hukumnya ...",
    options: ["Wajib", "Haram", "Makruh", "Sunnah"],
    correct: 3,
  },
  {
    level: "SD3",
    q: "I'tikaf dilakukan di ...",
    options: ["Rumah", "Masjid", "Sekolah", "Kantor"],
    correct: 1,
  },
  {
    level: "SD3",
    q: "Makan sahur sebaiknya dilakukan menjelang ...",
    options: ["Maghrib", "Subuh", "Dzuhur", "Ashar"],
    correct: 1,
  },
  {
    level: "SD3",
    q: "Orang haid wajib ...",
    options: [
      "Tetap puasa",
      "Diam saja",
      "Membayar zakat",
      "Tidak puasa dan mengganti",
    ],
    correct: 3,
  },
  {
    level: "SD3",
    q: "Menahan marah saat puasa mendapat ...",
    options: ["Dosa", "Pahala", "Hukuman", "Teguran"],
    correct: 1,
  },
  {
    level: "SD3",
    q: "Puasa melatih kepedulian kepada ...",
    options: ["Orang miskin", "Orang kaya", "Guru", "Teman saja"],
    correct: 0,
  },
  {
    level: "SD3",
    q: "Bulan Ramadhan disebut juga bulan Al-Qur'an karena ...",
    options: [
      "Al-Qur'an diturunkan",
      "Banyak hujan",
      "Libur panjang",
      "Ada haji",
    ],
    correct: 0,
  },

  /* ================= SD4 ================= */
  {
    level: "SD4",
    q: "Dalil kewajiban puasa terdapat dalam Al-Qur'an surat ...",
    options: ["Al-Ikhlas", "An-Nas", "Al-Kautsar", "Al-Baqarah 183"],
    correct: 3,
  },
  {
    level: "SD4",
    q: "Puasa Ramadhan diwajibkan bagi orang yang sudah ...",
    options: ["Baligh dan berakal", "Kaya saja", "Pintar", "Tinggi"],
    correct: 0,
  },
  {
    level: "SD4",
    q: "Orang yang tidak mampu berpuasa karena tua wajib membayar ...",
    options: ["Zakat", "Fidyah", "Kafarat", "Sedekah biasa"],
    correct: 1,
  },
  {
    level: "SD4",
    q: "Menahan diri dari hal yang membatalkan puasa disebut ...",
    options: ["Niat", "Imsak", "Shaum", "Zakat"],
    correct: 2,
  },
  {
    level: "SD4",
    q: "Lailatul Qadar lebih baik dari ... bulan",
    options: ["100", "1000", "10", "1"],
    correct: 1,
  },
  {
    level: "SD4",
    q: "Orang yang sengaja membatalkan puasa tanpa alasan berdosa dan wajib ...",
    options: [
      "Diam saja",
      "Membayar zakat",
      "Tidak apa-apa",
      "Mengganti puasa",
    ],
    correct: 3,
  },
  {
    level: "SD4",
    q: "Kafarat berlaku bagi orang yang ...",
    options: [
      "Lupa makan",
      "Sakit",
      "Safar",
      "Berhubungan suami istri di siang hari",
    ],
    correct: 3,
  },
  {
    level: "SD4",
    q: "Sholat tarawih dilakukan pada malam hari bulan ...",
    options: ["Muharram", "Ramadhan", "Rajab", "Safar"],
    correct: 1,
  },
  {
    level: "SD4",
    q: "Nuzulul Qur'an diperingati pada tanggal ... Ramadhan",
    options: ["10", "17", "21", "27"],
    correct: 1,
  },
  {
    level: "SD4",
    q: "I'tikaf dilakukan terutama pada ...",
    options: [
      "10 hari pertama",
      "10 hari pertengahan",
      "10 hari terakhir",
      "Akhir Syawal",
    ],
    correct: 2,
  },
  {
    level: "SD4",
    q: "Orang yang haid tidak berpuasa dan wajib ...",
    options: [
      "Membayar fidyah",
      "Tidak apa-apa",
      "Membayar zakat",
      "Mengganti puasa",
    ],
    correct: 3,
  },
  {
    level: "SD4",
    q: "Puasa sunnah enam hari di bulan Syawal pahalanya seperti puasa ...",
    options: ["Satu bulan", "Setahun", "Sepuluh hari", "Seratus hari"],
    correct: 1,
  },
  {
    level: "SD4",
    q: "Puasa melatih kita untuk mengendalikan ...",
    options: ["Emosi dan hawa nafsu", "Teman", "Guru", "Orang tua"],
    correct: 0,
  },
  {
    level: "SD4",
    q: "Berbuka puasa dianjurkan dengan makanan yang ...",
    options: ["Asin", "Pedas", "Pahit", "Manis"],
    correct: 3,
  },
  {
    level: "SD4",
    q: "Puasa adalah ibadah yang pahalanya langsung dibalas oleh ...",
    options: ["Malaikat", "Manusia", "Allah SWT", "Guru"],
    correct: 2,
  },

  /* ================= SD5 ================= */
  {
    level: "SD5",
    q: "Puasa termasuk ibadah yang bersifat ...",
    options: [
      "Lahiriah saja",
      "Batiniah saja",
      "Lahir dan batin",
      "Tidak keduanya",
    ],
    correct: 2,
  },
  {
    level: "SD5",
    q: "Rukun puasa ada ...",
    options: ["Satu", "Dua", "Tiga", "Empat"],
    correct: 1,
  },
  {
    level: "SD5",
    q: "Rukun puasa adalah niat dan ...",
    options: ["Makan sahur", "Tarawih", "Zakat", "Menahan diri"],
    correct: 3,
  },
  {
    level: "SD5",
    q: "Orang yang bepergian jauh disebut ...",
    options: ["Musafir", "Mukim", "Muallaf", "Miskin"],
    correct: 0,
  },
  {
    level: "SD5",
    q: "Batas minimal jarak safar yang membolehkan tidak puasa sekitar ... km",
    options: ["10", "25", "80", "5"],
    correct: 2,
  },
  {
    level: "SD5",
    q: "Orang yang sakit parah dan tidak mampu puasa wajib ...",
    options: ["Mengganti puasa", "Fidyah", "Tidak apa-apa", "Sedekah biasa"],
    correct: 1,
  },
  {
    level: "SD5",
    q: "Puasa Arafah dilakukan pada tanggal ... Dzulhijjah",
    options: ["7", "8", "9", "10"],
    correct: 2,
  },
  {
    level: "SD5",
    q: "Puasa Asyura dilakukan pada tanggal ... Muharram",
    options: ["1", "9 dan 10", "12", "15"],
    correct: 1,
  },
  {
    level: "SD5",
    q: "Hikmah puasa salah satunya adalah meningkatkan ...",
    options: ["Kesombongan", "Kemalasan", "Kemewahan", "Ketakwaan"],
    correct: 3,
  },
  {
    level: "SD5",
    q: "Puasa yang dilakukan untuk membayar nazar disebut puasa ...",
    options: ["Wajib", "Sunnah", "Makruh", "Haram"],
    correct: 0,
  },
  {
    level: "SD5",
    q: "Orang yang muntah tidak sengaja saat puasa maka puasanya ...",
    options: ["Batal", "Tetap sah", "Makruh", "Harus ulang"],
    correct: 1,
  },
  {
    level: "SD5",
    q: "Berlebih-lebihan saat berbuka hukumnya ...",
    options: ["Sunnah", "Wajib", "Haram", "Makruh"],
    correct: 3,
  },
  {
    level: "SD5",
    q: "Zakat fitrah wajib dibayarkan oleh setiap ...",
    options: ["Muslim", "Orang kaya saja", "Anak kecil saja", "Laki-laki saja"],
    correct: 0,
  },
  {
    level: "SD5",
    q: "Waktu pembayaran zakat fitrah paling akhir sebelum ...",
    options: ["Maghrib", "Subuh", "Sholat Id", "Tarawih"],
    correct: 2,
  },
  {
    level: "SD5",
    q: "Puasa melatih rasa empati kepada ...",
    options: ["Orang miskin", "Teman saja", "Guru saja", "Orang kaya"],
    correct: 0,
  },

  /* ================= SD6 ================= */
  {
    level: "SD6",
    q: "Puasa Ramadhan diwajibkan pada tahun ke ... Hijriyah",
    options: ["1", "2", "3", "4"],
    correct: 1,
  },
  {
    level: "SD6",
    q: "Salah satu syarat wajib puasa adalah ...",
    options: ["Baligh", "Kaya", "Pintar", "Sehat selalu"],
    correct: 0,
  },
  {
    level: "SD6",
    q: "Orang gila tidak wajib puasa karena tidak memiliki ...",
    options: ["Harta", "Kekuatan", "Waktu", "Akal"],
    correct: 3,
  },
  {
    level: "SD6",
    q: "Wanita hamil boleh tidak berpuasa jika khawatir terhadap ...",
    options: ["Dirinya atau bayinya", "Cuaca", "Sekolah", "Temannya"],
    correct: 0,
  },
  {
    level: "SD6",
    q: "Jika seseorang meninggal dan masih memiliki hutang puasa, maka ...",
    options: [
      "Tidak perlu diganti",
      "Dibayarkan fidyah oleh keluarganya",
      "Dibiarkan saja",
      "Wajib haji",
    ],
    correct: 1,
  },
  {
    level: "SD6",
    q: "Puasa sunnah yang dilarang dilakukan pada hari ...",
    options: ["Senin", "Kamis", "Idul Fitri", "Arafah"],
    correct: 2,
  },
  {
    level: "SD6",
    q: "Hari tasyrik terjadi pada tanggal ... Dzulhijjah",
    options: ["1-2", "9-10", "27-28", "11-12-13"],
    correct: 3,
  },
  {
    level: "SD6",
    q: "Orang yang membatalkan puasa karena lupa maka puasanya ...",
    options: ["Batal", "Sah dan dilanjutkan", "Harus mengganti", "Makruh"],
    correct: 1,
  },
  {
    level: "SD6",
    q: "Kafarat bagi yang melanggar puasa dengan sengaja adalah ...",
    options: [
      "Memberi makan 1 orang",
      "Puasa 60 hari berturut-turut",
      "Sedekah biasa",
      "Tidak apa-apa",
    ],
    correct: 1,
  },
  {
    level: "SD6",
    q: "Niat puasa Ramadhan sebaiknya dilakukan setiap ...",
    options: [
      "Awal bulan saja",
      "Setiap pagi",
      "Seminggu sekali",
      "Malam hari sebelum puasa",
    ],
    correct: 3,
  },
  {
    level: "SD6",
    q: "Imsak berarti ...",
    options: ["Makan banyak", "Menahan diri", "Berbuka", "Tidur"],
    correct: 1,
  },
  {
    level: "SD6",
    q: "Puasa qadha adalah puasa untuk ...",
    options: [
      "Mengganti puasa yang ditinggalkan",
      "Puasa sunnah",
      "Puasa nazar saja",
      "Puasa Syawal",
    ],
    correct: 0,
  },
  {
    level: "SD6",
    q: "Puasa nazar hukumnya menjadi ...",
    options: ["Sunnah", "Wajib", "Makruh", "Haram"],
    correct: 1,
  },
  {
    level: "SD6",
    q: "Menyegerakan berbuka termasuk ...",
    options: ["Makruh", "Haram", "Adab puasa", "Tidak penting"],
    correct: 2,
  },
  {
    level: "SD6",
    q: "Tujuan utama puasa adalah agar menjadi orang yang ...",
    options: ["Kaya", "Kuat", "Bertakwa", "Terkenal"],
    correct: 2,
  },

  /* ================= SMP ================= */
  {
    level: "SMP",
    q: "Dalil kewajiban puasa terdapat dalam QS Al-Baqarah ayat ...",
    options: ["180", "183", "190", "200"],
    correct: 1,
  },
  {
    level: "SMP",
    q: "Puasa diwajibkan agar manusia menjadi ...",
    options: ["Kuat", "Terkenal", "Bertakwa", "Kaya"],
    correct: 2,
  },
  {
    level: "SMP",
    q: "Orang yang sakit dan tidak mampu puasa wajib ...",
    options: [
      "Diam saja",
      "Tidak usah apa-apa",
      "Zakat",
      "Fidyah atau qadha sesuai kondisi",
    ],
    correct: 3,
  },
  {
    level: "SMP",
    q: "Berhubungan suami istri di siang hari Ramadhan menyebabkan ...",
    options: ["Makruh", "Kafarat besar", "Tidak apa-apa", "Sunnah"],
    correct: 1,
  },
  {
    level: "SMP",
    q: "Puasa melatih pengendalian terhadap ...",
    options: ["Harta", "Teman", "Guru", "Hawa nafsu"],
    correct: 3,
  },
  {
    level: "SMP",
    q: "Orang yang tidak berniat puasa di malam hari maka puasanya ...",
    options: ["Sah", "Batal menurut jumhur ulama", "Makruh", "Tetap sah"],
    correct: 1,
  },
  {
    level: "SMP",
    q: "Puasa sunnah enam hari di bulan Syawal jika digabung dengan Ramadhan seperti puasa ...",
    options: ["1 bulan", "6 bulan", "Setahun", "10 hari"],
    correct: 2,
  },
  {
    level: "SMP",
    q: "Lailatul Qadar lebih baik dari ...",
    options: ["100 hari", "1000 bulan", "100 bulan", "10 tahun"],
    correct: 1,
  },
  {
    level: "SMP",
    q: "I'tikaf disunnahkan terutama pada ...",
    options: [
      "10 awal Ramadhan",
      "10 pertengahan",
      "10 akhir Ramadhan",
      "Akhir Syawal",
    ],
    correct: 2,
  },
  {
    level: "SMP",
    q: "Puasa pada hari raya Idul Fitri hukumnya ...",
    options: ["Wajib", "Sunnah", "Makruh", "Haram"],
    correct: 3,
  },
  {
    level: "SMP",
    q: "Hikmah sosial puasa adalah ...",
    options: [
      "Menambah kekayaan",
      "Meningkatkan gengsi",
      "Mengurangi belajar",
      "Meningkatkan empati kepada fakir miskin",
    ],
    correct: 3,
  },
  {
    level: "SMP",
    q: "Orang yang meninggalkan puasa tanpa uzur berdosa dan wajib ...",
    options: ["Qadha dan taubat", "Fidyah saja", "Diam saja", "Tidak apa-apa"],
    correct: 0,
  },
  {
    level: "SMP",
    q: "Syarat sah puasa salah satunya adalah ...",
    options: ["Kaya", "Baligh", "Sehat selalu", "Islam"],
    correct: 3,
  },
  {
    level: "SMP",
    q: "Muntah yang disengaja saat puasa menyebabkan ...",
    options: ["Sah", "Batal", "Makruh", "Tidak apa-apa"],
    correct: 1,
  },
  {
    level: "SMP",
    q: "Puasa merupakan ibadah yang balasannya langsung dari ...",
    options: ["Malaikat", "Guru", "Allah SWT", "Manusia"],
    correct: 2,
  },
];
